name: elastic_drawer
description: Elastic Drawer - elastic panel that slides in horizontally to show
  fully customize content (navigation links, menu items, notes etc.)
version: 2.0.2
homepage: https://github.com/nevedomyy/elastic_drawer.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 1.0.4
  flutter_test:
    sdk: flutter
